version: '3.8'

services:
  downloader:
    build: .
    restart: unless-stopped
    ports:
      - "6068:6068"
    environment:
      - NODE_ENV=production
      - PORT=6068
      - BASE_URL=https://d.snaptik.fit  # Change this to your actual public URL in production
      - ENCRYPTION_KEY=overflow  # Change this to a secure key
      - DOUYIN_API_URL=http://douyin_tiktok_download_api:8000/api/hybrid/video_data  # Update this as needed
      - REDIS_URL=redis://redis:6379
      - CACHE_TTL=3600
      - DOCKER_ENV=true
      - USE_PROXY=true
    volumes:
      - ./temp:/app/temp
    networks:
      - tiktok_shared_network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - tiktok_shared_network
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  tiktok_shared_network:
    external: true
    name: tiktok_shared_network