version: '3.8'

services:
  downloader:
    build: .
    restart: unless-stopped
    ports:
      - "6068:6068"
    environment:
      - NODE_ENV=production
      - PORT=6068
      - BASE_URL=https://tt.snaptik.biz.id  # Change this to your actual public URL in production
      - ENCRYPTION_KEY=overflow  # Change this to a secure key
      - DOUYIN_API_URL=http://douyin_tiktok_download_api:8000/api/hybrid/video_data  # Update this as needed
    volumes:
      - ./temp:/app/temp
    networks:
      - tiktok_shared_network

networks:
  tiktok_shared_network:
    external: true
    name: tiktok_shared_network