version: "3.9"

services:
  douyin_tiktok_download_api:
    build: .
    container_name: douyin_tiktok_download_api
    restart: always
    ports:
      - "3035:8000"
    volumes:
      - ./douyin_tiktok_download_api/douyin_web/config.yaml:/app/crawlers/douyin/web/config.yaml
      - ./douyin_tiktok_download_api/tiktok_web/config.yaml:/app/crawlers/tiktok/web/config.yaml
      - ./douyin_tiktok_download_api/tiktok_app/config.yaml:/app/crawlers/tiktok/app/config.yaml
    environment:
      TZ: Asia/Jakarta
      PUID: 1026
      PGID: 100
    privileged: true
    networks:
      - tiktok_shared_network

  tiktok_gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: tiktok_gateway
    restart: always
    ports:
      - "8091:8089"
    volumes:
      - ./douyin_tiktok_download_api/douyin_web/config.yaml:/app/crawlers/douyin/web/config.yaml:ro
      - ./douyin_tiktok_download_api/tiktok_web/config.yaml:/app/crawlers/tiktok/web/config.yaml:ro
      - ./douyin_tiktok_download_api/tiktok_app/config.yaml:/app/crawlers/tiktok/app/config.yaml:ro
      - ./config.yaml:/app/config.yaml:ro
    environment:
      TZ: Asia/Jakarta
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8089"
      CONFIG_PATH: /app/config.yaml
    privileged: true
    networks:
      - tiktok_shared_network

networks:
  tiktok_shared_network:
    name: tiktok_shared_network
