version: '3'

services:
  tiktok-api:
    build: .
    container_name: tiktok-downloader-api
    ports:
      - "3029:3029"
    volumes:
      - ./temp:/app/temp
      - .:/app
    env_file:
      - .env
    environment:
      - BASE_URL=http://localhost:3029
      - DOUYIN_API_URL=http://douyin_tiktok_download_api:8000  # URL untuk akses ke API Douyin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - tiktok_shared_network

networks:
  tiktok_shared_network:
    external: true
    name: tiktok_shared_network